# Copyright ©2022, GM Consult (Pty) Ltd. All rights reserved
# End user is granted a non-exclusive non-transferable license the ("License")
# to use GM Consult's proprietary software (the "Software").

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    - prefer_final_locals

analyzer:
  exclude:
    # - lib/sample_data/data/**
  language:
    # strict-casts: true
    # strict-raw-types: true

# exclude:    - lib/sample_data/data/**