# Copyright ©2022, GM Consult (Pty) Ltd. All rights reserved
# End user is granted a non-exclusive non-transferable license the ("License")
# to use GM Consult's proprietary software (the "Software").

name: detectable_text_field
description: TextField with detection features. 
version: 2.1.0
homepage: https://github.com/santa112358/detectable_text_field

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.3"

dependencies:
  # ----------------------------------- SDK -----------------------------------
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
